[colors.bright]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#b4befe"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#cdd6f4"
text = "#1e1e2e"

[colors.normal]
black = "#1e1e2e"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.selection]
background = "#313244"
text = "#cdd6f4"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.5

[window.padding]
x = 10
y = 10

